name: re-tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: |
          Tag to be updated or created
        required: true
        default: 'v1'

permissions:
  contents: write

jobs:
  retag:
    name: Re-tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - run: |
        git push origin :refs/tags/${{ inputs.tag }}
        git tag -f ${{ inputs.tag }}
        git push origin main --tags
