name: Update Main Version
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      major_version:
        type: choice
        description: The major version to update
        options:
          - v3
          - v2
          - v1
      target:
        description: The tag or reference to use
        required: true

permissions:
  contents: write

jobs:
  tag:
    uses: actions-mn/shared/.github/workflows/update-major-version.yml@main
    with:
      major_version: ${{ inputs.major_version }}
      target: ${{ inputs.target }}
